### ISSUE TITLE
Star This Repo 

### ISSUE THREAD

**Issue by mubaris** [gostudent/gostudent.github.io#1]
Post Screenshots

**Comment by adityaraj-xtc** [comment]
![go](https://user-images.githubusercontent.com/34164978/34838488-50180128-f724-11e7-8110-b19fc2111726.png)

**Comment by amriteshbhaskar** [comment]
![starthisrepo](https://user-images.githubusercontent.com/34058250/34838744-41a3d940-f725-11e7-8a9b-7c4514283eab.png)

**Comment by GOVINDDIXIT** [comment]
![captures](https://user-images.githubusercontent.com/32304546/34839211-cfadb53e-f726-11e7-8e1c-d66bec52c898.PNG)

**Comment by ananya** [comment]
![a](https://user-images.githubusercontent.com/33188930/34839371-6911f3c0-f727-11e7-8232-af0b3e50c114.png)

**Comment by YashRE42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34839375-6d1b6be0-f727-11e7-8420-998292d75f3f.png)

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34840709-d3d3b492-f72b-11e7-97ab-4a047f34ae0b.png)

**Comment by rahulkumaran** [comment]
![screenshot from 2018-01-12 00-10-18](https://user-images.githubusercontent.com/26206171/34841073-038b7ba6-f72d-11e7-925b-c70eab44294d.png)

**Comment by strikertanmay** [comment]
![screenshot from 2018-01-12 02-21-50](https://user-images.githubusercontent.com/32292953/34846825-6ccc836e-f73f-11e7-8b38-5d91bdb125f5.png)

**Comment by AK-007** [comment]
![screenshot 56](https://user-images.githubusercontent.com/26346816/34848385-92d8d21a-f744-11e7-8a22-4dc9787b2338.png)

**Comment by vvvinamer** [comment]
![screenshot 34](https://user-images.githubusercontent.com/35339278/34868759-d87b557a-f7aa-11e7-88e5-61d3a590070a.png)

**Comment by AlphaCholera** [comment]
![screenshot from 2018-01-12 22-14-18](https://user-images.githubusercontent.com/33174671/34872681-e1afe964-f7b7-11e7-824b-8be472ca8fab.png)
